#![allow(deprecated)]  // aya renames Bpf → Ebpf in newer versions

mod bpf;
mod proc;

use bpf::BpfRuntime;
use clap::{Parser, Subcommand};
use spica_common::{LkmEvent, ProcessInfo};
use spica_detect::{Detection, DetectionClass, ProcessRecord, ProcessRegistry};
use std::fs;
use std::time::{Duration, Instant};
use tokio::signal::unix::{signal, SignalKind};

// Compile-time fallback key generated by build.rs from /dev/urandom.
// Used only if spica_key::resolve() falls back (TPM unavailable, non-Linux host).
include!(concat!(env!("OUT_DIR"), "/keys.rs"));

const TICK_RATE_MS: u64 = 100;

#[derive(Parser)]
#[command(version, about = "SPiCa — System Process Integrity & Cross-view Analysis")]
struct Cli {
    /// Subcommand. If omitted, SPiCa runs detection (default behavior).
    #[command(subcommand)]
    command: Option<Command>,
}

#[derive(Subcommand)]
enum Command {
    /// Install SPiCa to /usr/local/bin and integrate with initramfs (requires root).
    /// Auto-detects Debian (initramfs-tools) or Fedora (dracut).
    Install,

    /// Remove SPiCa and its initramfs integration (requires root).
    /// Rebuilds the initramfs so the next boot doesn't reference removed hooks.
    Uninstall,
}

fn main() -> Result<(), anyhow::Error> {
    let cli = Cli::parse();
    match cli.command {
        Some(Command::Install)   => return spica_install::install().map_err(Into::into),
        Some(Command::Uninstall) => return spica_install::uninstall().map_err(Into::into),
        None => {}  // fall through to normal detection run
    }
    // The detection loop is async — hand off to a tokio runtime.
    tokio::runtime::Builder::new_multi_thread()
        .enable_all()
        .build()?
        .block_on(run_detection())
}

async fn run_detection() -> Result<(), anyhow::Error> {
    // 1. Watchdog — check for leftover pin from a previously-killed instance.
    if bpf::watchdog_pin_exists() {
        println!("[WATCHDOG]   Previous SPiCa instance was not cleanly terminated — possible SIGKILL or crash");
        bpf::clear_watchdog_pin();
    }

    // 2. Security stack audit (Secure Boot / module signing / IMA / BPF LSM).
    spica_seccheck::run();

    // 3. Resolve the XOR key — TPM first, visible INSECURE MODE fallback.
    let (base_key, origin) = spica_key::resolve(COMPILE_TIME_BASE_KEY);
    if origin == spica_key::KeyOrigin::Tpm {
        println!("[KEY]        TPM key loaded");
    }

    // Derive the integrity canary via SipHash-1-3(BASE_KEY, "SPiCaINT").
    // Written to both .bss INTEGRITY_TOKEN (unreachable) and sc_canary (named
    // map, the tamper target). Divergence between them triggers [TAMPER].
    let integrity_token = spica_key::derive_integrity_token(base_key);

    // 4. Load the eBPF runtime (load programs, set globals, attach, pin watchdog).
    let (mut rt, lsm_attached) =
        BpfRuntime::load(base_key, std::process::id(), integrity_token)?;
    if lsm_attached {
        rt.lock_lsm_gate()?;
        println!("[LSM]        Module loading locked — no new LKMs permitted");
    } else {
        eprintln!("[LSM]        BPF LSM unavailable — kernel needs CONFIG_BPF_LSM + lsm=bpf; module blocking disabled");
    }

    // 5. Seed the process registry from /proc. Treat every currently-visible
    //    process as "observed at startup" so they don't trip GHOST.
    let mut registry: ProcessRegistry = Default::default();
    let startup = Instant::now();
    for tgid in proc::read_tgids() {
        registry.insert(tgid, ProcessRecord::seeded(0));
    }

    // Time helper: nanos since startup, floored to 1 to avoid colliding with
    // the "never seen" sentinel (0) used inside spica-detect.
    let nanos_since_startup = || {
        let n = Instant::now().duration_since(startup).as_nanos() as u64;
        n.max(1)
    };

    println!("I'm going to sing, so shine bright, SPiCa...");

    // 6. Event loop. Ring buffer polling lives here (tokio::select! needs
    //    direct AsyncFd guard access); detection logic lives in spica-detect.
    let mut alerts: Vec<Detection> = Vec::new();
    let mut tick = tokio::time::interval(Duration::from_millis(TICK_RATE_MS));
    tick.set_missed_tick_behavior(tokio::time::MissedTickBehavior::Skip);
    let mut sigterm = signal(SignalKind::terminate())?;

    loop {
        tokio::select! {
            guard = rt.sched_rb_mut().readable_mut() => {
                let mut guard = guard?;
                let rb = guard.get_inner_mut();
                while let Some(item) = rb.next() {
                    let raw = unsafe { &*(item.as_ptr() as *const ProcessInfo) };
                    // event_type is read before deobfuscation (it is never XOR'd).
                    if raw.event_type == 0 {
                        let mut info = *raw;
                        spica_common::xor_fields(&mut info, base_key);
                        if let Some(d) = spica_detect::on_sched_event(
                            info, &mut registry, nanos_since_startup(),
                        ) {
                            print_detection(&d);
                        }
                    }
                }
                guard.clear_ready();
            }
            guard = rt.nmi_rb_mut().readable_mut() => {
                let mut guard = guard?;
                let rb = guard.get_inner_mut();
                while let Some(item) = rb.next() {
                    let raw = unsafe { &*(item.as_ptr() as *const ProcessInfo) };
                    if raw.event_type == 1 {
                        // Canary mismatch sentinel — rootkit intercepted the
                        // bpf_map_update_elem call for the integrity canary.
                        // Distinct from FSM-driven TAMPER (which fires when
                        // NMI is alive but sched is silent); this one is the
                        // direct map-tamper signal from the NMI program.
                        println!("[TAMPER]     BPF map integrity check failed — sc_canary intercepted");
                    } else {
                        let mut info = *raw;
                        spica_common::xor_fields(&mut info, base_key);
                        spica_detect::on_nmi_event(
                            info, &mut registry, nanos_since_startup(),
                        );
                    }
                }
                guard.clear_ready();
            }
            guard = rt.lsm_rb_mut().readable_mut() => {
                let mut guard = guard?;
                let rb = guard.get_inner_mut();
                while let Some(item) = rb.next() {
                    let ev = unsafe { &*(item.as_ptr() as *const LkmEvent) };
                    let d = spica_detect::on_lkm_event(*ev);
                    print_detection(&d);
                }
                guard.clear_ready();
            }
            _ = tick.tick() => {
                let proc_tgids = proc::read_tgids();
                let now = nanos_since_startup();
                spica_detect::evaluate(&mut registry, &proc_tgids, now, &mut alerts);
                for d in &alerts {
                    print_detection(d);
                }
            }
            _ = sigterm.recv() => break,
            _ = tokio::signal::ctrl_c() => break,
        }
    }

    println!("Catch me! I'll leap over Denebola");
    bpf::clear_watchdog_pin();

    Ok(())
}

// ── Helpers ───────────────────────────────────────────────────────────────────

fn print_detection(d: &Detection) {
    // LKM events fold the calling process's comm into the details string at
    // the source (on_lkm_event in spica-detect) because /proc/<tgid>/comm
    // can't be reliably read after the fact — insmod/modprobe often exit
    // before we print. Skip the comm column for those classes.
    match d.class {
        DetectionClass::LkmAllow | DetectionClass::LkmDeny => {
            println!("[{:<10}] tgid:{:<6} {}",
                d.class.label(), d.tgid, d.details);
        }
        _ => {
            let comm = resolve_comm(d.tgid);
            println!("[{:<10}] tgid:{:<6} {:<16} {}",
                d.class.label(), d.tgid, comm, d.details);
        }
    }
}

fn resolve_comm(tgid: u32) -> String {
    fs::read_to_string(format!("/proc/{}/comm", tgid))
        .unwrap_or_else(|_| "???".into())
        .trim()
        .to_string()
}
