#![allow(deprecated)]  // aya renames Bpf → Ebpf in newer versions

mod bpf;
mod proc;

use bpf::BpfRuntime;
use clap::{Parser, Subcommand};
use spica_common::{LkmEvent, ProcessInfo};
use spica_detect::{ChannelCooldown, Detection, DetectionClass, ProcessRecord, ProcessRegistry};
use std::fs;
use std::time::{Duration, Instant};
use tokio::signal::unix::{signal, SignalKind};

// Compile-time fallback key generated by build.rs from /dev/urandom.
// Used only if spica_key::resolve() falls back (TPM unavailable, non-Linux host).
include!(concat!(env!("OUT_DIR"), "/keys.rs"));

const TICK_RATE_MS: u64 = 100;

#[derive(Parser)]
#[command(version, about = "SPiCa — System Process Integrity & Cross-view Analysis")]
struct Cli {
    /// Subcommand. If omitted, SPiCa runs detection (default behavior).
    #[command(subcommand)]
    command: Option<Command>,
}

#[derive(Subcommand)]
enum Command {
    /// Install SPiCa to /usr/local/bin and integrate with initramfs (requires root).
    /// Auto-detects Debian (initramfs-tools) or Fedora (dracut).
    Install,

    /// Remove SPiCa and its initramfs integration (requires root).
    /// Rebuilds the initramfs so the next boot doesn't reference removed hooks.
    Uninstall,
}

fn main() -> Result<(), anyhow::Error> {
    let cli = Cli::parse();
    match cli.command {
        Some(Command::Install)   => return spica_install::install().map_err(Into::into),
        Some(Command::Uninstall) => return spica_install::uninstall().map_err(Into::into),
        None => {}  // fall through to normal detection run
    }
    // The detection loop is async — hand off to a tokio runtime.
    tokio::runtime::Builder::new_multi_thread()
        .enable_all()
        .build()?
        .block_on(run_detection())
}

async fn run_detection() -> Result<(), anyhow::Error> {
    // 1. Watchdog — check for leftover pin from a previously-killed instance.
    if bpf::watchdog_pin_exists() {
        println!("[WATCHDOG]   Previous SPiCa instance was not cleanly terminated — possible SIGKILL or crash");
        bpf::clear_watchdog_pin();
    }

    // 2. Security stack audit (Secure Boot / module signing / IMA / BPF LSM).
    spica_seccheck::run();

    // 3. Resolve the XOR key — TPM first, visible INSECURE MODE fallback.
    let (base_key, origin) = spica_key::resolve(COMPILE_TIME_BASE_KEY);
    if origin == spica_key::KeyOrigin::Tpm {
        println!("[KEY]        TPM key loaded");
    }

    // 4. Load the eBPF runtime (load programs, set globals, attach, pin watchdog).
    let (mut rt, lsm_attached) =
        BpfRuntime::load(base_key, std::process::id())?;
    if lsm_attached {
        rt.lock_lsm_gate()?;
        println!("[LSM]        Module loading locked — no new LKMs permitted");
    } else {
        eprintln!("[LSM]        BPF LSM unavailable — kernel needs CONFIG_BPF_LSM + lsm=bpf; module blocking disabled");
    }

    // 5. Seed the process registry from /proc. Treat every currently-visible
    //    process as "observed at startup" so they don't trip GHOST.
    let mut registry: ProcessRegistry = Default::default();
    let startup = Instant::now();
    for tgid in proc::read_tgids() {
        registry.insert(tgid, ProcessRecord::seeded(0));
    }

    // Time helper: nanos since startup, floored to 1 to avoid colliding with
    // the "never seen" sentinel (0) used inside spica-detect.
    let nanos_since_startup = || {
        let n = Instant::now().duration_since(startup).as_nanos() as u64;
        n.max(1)
    };

    println!("I'm going to sing, so shine bright, SPiCa...");

    // 6. Event loop. Ring buffer polling lives here (tokio::select! needs
    //    direct AsyncFd guard access); detection logic lives in spica-detect.
    let mut alerts: Vec<Detection> = Vec::new();
    let mut channel_cd = ChannelCooldown::default();
    let mut last_nmi_hb: u64 = 0;
    let mut pid_tgid_cache: std::collections::HashMap<u32, u32> = std::collections::HashMap::new();
    let mut tick_count: u64 = 0;
    let mut tick = tokio::time::interval(Duration::from_millis(TICK_RATE_MS));
    tick.set_missed_tick_behavior(tokio::time::MissedTickBehavior::Skip);
    let mut sigterm = signal(SignalKind::terminate())?;

    loop {
        let (sched_rb, nmi_rb, lsm_rb) = rt.split_ring_buffers();
        tokio::select! {
            guard = sched_rb.readable_mut() => {
                let mut guard = guard?;
                let rb = guard.get_inner_mut();
                while let Some(item) = rb.next() {
                    let raw = unsafe { &*(item.as_ptr() as *const ProcessInfo) };
                    // event_type is read before deobfuscation (it is never XOR'd).
                    if raw.event_type == 0 {
                        let mut info = *raw;
                        spica_common::xor_fields(&mut info, base_key);
                        // The tracepoint reports the thread ID (next_pid),
                        // not the TGID. For multi-threaded processes, the
                        // thread ID differs from the TGID that /proc lists.
                        // Resolve via /proc/<pid>/status with a cache so
                        // each unique thread ID triggers at most one read.
                        // If /proc/<pid> doesn't exist, the process is either
                        // hidden (DKOM candidate) or already exited — use
                        // the PID as the TGID so DKOM detection can evaluate it.
                        let resolved_tgid = if let Some(&t) = pid_tgid_cache.get(&info.pid) {
                            t
                        } else {
                            let t = proc::resolve_tgid(info.pid).unwrap_or(info.pid);
                            pid_tgid_cache.insert(info.pid, t);
                            t
                        };
                        info.tgid = resolved_tgid;
                        if let Some(d) = spica_detect::on_sched_event(
                            info, &mut registry, nanos_since_startup(),
                        ) {
                            print_detection(&d);
                        }
                    }
                }
                guard.clear_ready();
            }
            guard = nmi_rb.readable_mut() => {
                let mut guard = guard?;
                let rb = guard.get_inner_mut();
                while let Some(item) = rb.next() {
                    let raw = unsafe { &*(item.as_ptr() as *const ProcessInfo) };
                    // event_type is read before deobfuscation (never XOR'd).
                    if raw.event_type == 1 {
                        // sched_switch heartbeat frozen — tracepoint detached,
                        // suppressed, or BTF/attach failure. This is the direct
                        // integrity signal from the NMI program's .bss check.
                        println!("[TAMPER]     sched_switch heartbeat frozen — tracepoint compromised");
                    }
                    // Both event_type=0 (heartbeat) and event_type=1 (tamper)
                    // prove the NMI channel is alive. Update last_nmi_hb.
                    last_nmi_hb = nanos_since_startup();
                }
                guard.clear_ready();
            }
            guard = lsm_rb.readable_mut() => {
                let mut guard = guard?;
                let rb = guard.get_inner_mut();
                while let Some(item) = rb.next() {
                    let ev = unsafe { &*(item.as_ptr() as *const LkmEvent) };
                    let d = spica_detect::on_lkm_event(*ev);
                    print_detection(&d);
                }
                guard.clear_ready();
            }
            _ = tick.tick() => {
                let proc_tgids = proc::read_tgids();
                let now = nanos_since_startup();
                // Periodically clear the PID→TGID cache to reclaim memory
                // from exited threads and handle PID recycling.
                tick_count += 1;
                if tick_count % 300 == 0 {
                    pid_tgid_cache.clear();
                }
                spica_detect::evaluate(
                    &mut registry, &proc_tgids, now, last_nmi_hb,
                    &mut channel_cd, &mut alerts,
                );
                for d in &alerts {
                    print_detection(d);
                }
            }
            _ = sigterm.recv() => break,
            _ = tokio::signal::ctrl_c() => break,
        }
    }

    println!("Catch me! I'll leap over Denebola");
    bpf::clear_watchdog_pin();

    Ok(())
}

// ── Helpers ───────────────────────────────────────────────────────────────────

fn print_detection(d: &Detection) {
    // LKM events fold the calling process's comm into the details string at
    // the source (on_lkm_event in spica-detect) because /proc/<tgid>/comm
    // can't be reliably read after the fact — insmod/modprobe often exit
    // before we print. Skip the comm column for those classes.
    match d.class {
        DetectionClass::LkmAllow | DetectionClass::LkmDeny => {
            println!("[{:<10}] tgid:{:<6} {}",
                d.class.label(), d.tgid, d.details);
        }
        _ => {
            let comm = resolve_comm(d.tgid);
            println!("[{:<10}] tgid:{:<6} {:<16} {}",
                d.class.label(), d.tgid, comm, d.details);
        }
    }
}

fn resolve_comm(tgid: u32) -> String {
    fs::read_to_string(format!("/proc/{}/comm", tgid))
        .unwrap_or_else(|_| "???".into())
        .trim()
        .to_string()
}
