#![no_std]
#![no_main]
#![allow(static_mut_refs)]

// vmlinux.rs is generated by: cargo run --package xtask generate-vmlinux
// It is kernel-version-specific and gitignored; regenerate on each host.
mod vmlinux;
use vmlinux::task_struct;

use aya_ebpf::{
    macros::{btf_tracepoint, map, perf_event},
    maps::RingBuf,
    programs::{BtfTracePointContext, PerfEventContext},
    helpers::{bpf_ktime_get_ns, bpf_probe_read_kernel, bpf_get_current_task},
};
use spica_common::ProcessInfo;

#[allow(non_upper_case_globals)]
#[unsafe(export_name = "license")]
pub static _license: [u8; 4] = *b"GPL\0";

/// RingBuf for sched_switch BTF tracepoint events.
#[map]
static mut EVENTS_SCHED: RingBuf = RingBuf::with_byte_size(256 * 1024, 0);

/// RingBuf for NMI perf-event observations.
#[map]
static mut EVENTS_NMI: RingBuf = RingBuf::with_byte_size(256 * 1024, 0);

// ---------------------------------------------------------------------------
// Program 1: sched_switch BTF tracepoint
//
// BTF signature: (bool preempt, struct task_struct *prev, struct task_struct *next)
// We read `next` (arg index 2) via CO-RE to get the process being scheduled IN.
// This avoids bpf_get_current_pid_tgid() / bpf_get_current_comm() which return
// the *outgoing* task at sched_switch time and are attackable via hooking.
// ---------------------------------------------------------------------------
#[btf_tracepoint(function = "sched_switch")]
pub fn spica_sched(ctx: BtfTracePointContext) -> u32 {
    match try_sched(ctx) {
        Ok(ret) => ret,
        Err(_) => 0,
    }
}

fn try_sched(ctx: BtfTracePointContext) -> Result<u32, i64> {
    // arg(2) = *next (task being scheduled in)
    let next: *const task_struct = unsafe { ctx.arg(2) };
    if next.is_null() {
        return Ok(0);
    }

    let pid: u32 = unsafe { bpf_probe_read_kernel::<i32>(&(*next).pid as *const _)? } as u32;
    let tgid: u32 = unsafe { bpf_probe_read_kernel::<i32>(&(*next).tgid as *const _)? } as u32;
    let comm: [u8; 16] = unsafe { core::mem::transmute(bpf_probe_read_kernel::<[i8; 16]>(&(*next).comm as *const _)?) };

    // pid == 0 is the idle task; skip it.
    if pid == 0 {
        return Ok(0);
    }

    let time = unsafe { bpf_ktime_get_ns() };

    let info = ProcessInfo { pid, tgid, comm, last_seen: time };

    if let Some(mut entry) = unsafe { EVENTS_SCHED.reserve::<ProcessInfo>(0) } {
        entry.write(info);
        entry.submit(0);
    }

    Ok(0)
}

// ---------------------------------------------------------------------------
// Program 2: NMI perf-event (hardware CPU cycle counter)
//
// Fired via Non-Maskable Interrupt — cannot be masked by `cli` or RFLAGS.IF.
// Requires PMU hardware reprogramming to suppress, making it a second,
// independent observation channel resistant to software-only hooking attacks.
//
// At NMI context, bpf_get_current_task() correctly identifies the interrupted
// task. This is not subject to the same execution-context spoofing that
// bpf_get_current_pid_tgid() is vulnerable to at tracepoint context.
// ---------------------------------------------------------------------------
#[perf_event]
pub fn spica_nmi(ctx: PerfEventContext) -> u32 {
    match try_nmi(ctx) {
        Ok(ret) => ret,
        Err(_) => 0,
    }
}

fn try_nmi(_ctx: PerfEventContext) -> Result<u32, i64> {
    let task = unsafe { bpf_get_current_task() as *const task_struct };
    if task.is_null() {
        return Ok(0);
    }

    let pid: u32 = unsafe { bpf_probe_read_kernel::<i32>(&(*task).pid as *const _)? } as u32;
    let tgid: u32 = unsafe { bpf_probe_read_kernel::<i32>(&(*task).tgid as *const _)? } as u32;
    let comm: [u8; 16] = unsafe { core::mem::transmute(bpf_probe_read_kernel::<[i8; 16]>(&(*task).comm as *const _)?) };

    if pid == 0 {
        return Ok(0);
    }

    let time = unsafe { bpf_ktime_get_ns() };

    let info = ProcessInfo { pid, tgid, comm, last_seen: time };

    if let Some(mut entry) = unsafe { EVENTS_NMI.reserve::<ProcessInfo>(0) } {
        entry.write(info);
        entry.submit(0);
    }

    Ok(0)
}

#[panic_handler]
fn panic(_info: &core::panic::PanicInfo) -> ! {
    unsafe { core::hint::unreachable_unchecked() }
}
