//! SPiCa key management — TPM-sourced obfuscation key + visible fallback.
//!
//! Resolves the 64-bit XOR key at startup. Tries the hardware TPM first
//! (Linux-only, via `tss-esapi`); on any failure (no TPM, command error,
//! non-Linux host) falls back to a per-build compile-time key with a
//! visibly loud `INSECURE MODE` banner so operators notice.
//!
//! Also owns `derive_integrity_token` — a SipHash-1-3 MAC over `BASE_KEY`
//! used as the integrity canary. This is a *correct* MAC use case (unlike
//! XOR obfuscation which is just read-leakage defense — see spica-common).
//!
//! See docs/superpowers/specs/2026-06-20-spica-v4-refactor-design.md §7-8.

use siphasher::sip::SipHasher13;
use std::hash::Hasher;

// ── Trait + error types ──────────────────────────────────────────────────────

/// Source of the 64-bit XOR obfuscation key.
///
/// Production impls:
/// - `TpmKeySource` (Linux-only) — reads 8 bytes from `TPM2_GetRandom`
/// - `CompileTimeKey(u64)` — returns the per-build fallback constant
///
/// Test impl:
/// - `StaticKey(u64)` — deterministic value for unit tests
pub trait KeySource {
    fn get_random_key(&mut self) -> Result<u64, KeyError>;
}

#[derive(Debug)]
pub enum KeyError {
    TpmUnavailable,
    TpmCommandFailed(String),
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum KeyOrigin {
    Tpm,
    CompileTime,
}

// ── CompileTimeKey (fallback, all platforms) ─────────────────────────────────

/// Fallback key source: returns a fixed `u64` baked at build time.
///
/// The build script in the `spica` crate generates this from `/dev/urandom`
/// and passes it in via the `COMPILE_TIME_BASE_KEY` const from `OUT_DIR/keys.rs`.
/// `spica-key` itself has no build script — the caller wires the constant in.
pub struct CompileTimeKey(pub u64);

impl KeySource for CompileTimeKey {
    fn get_random_key(&mut self) -> Result<u64, KeyError> {
        Ok(self.0)
    }
}

// ── TpmKeySource (Linux-only) ────────────────────────────────────────────────

#[cfg(target_os = "linux")]
pub use linux_tpm::*;

#[cfg(target_os = "linux")]
mod linux_tpm {
    use super::{KeyError, KeySource};

    /// Production TPM key source: opens `/dev/tpmrm0` via the TSS Enhanced
    /// System API and calls `GetRandom(8)`. No subprocess, no pipe transit,
    /// no command line visible to other processes.
    pub struct TpmKeySource {
        ctx: tss_esapi::Context,
    }

    impl TpmKeySource {
        pub fn new() -> Result<Self, KeyError> {
            // TctiNamePts::Device opens the kernel resource manager path
            // (/dev/tpmrm0). Fails cleanly if no TPM is present.
            let ctx = tss_esapi::Context::new(
                tss_esapi::tcti_ldr::TctiNamePts::from_string_with_default("device"),
            )
            .map_err(|_| KeyError::TpmUnavailable)?;
            Ok(Self { ctx })
        }
    }

    impl KeySource for TpmKeySource {
        fn get_random_key(&mut self) -> Result<u64, KeyError> {
            let bytes = self.ctx
                .get_random(8)
                .map_err(|e| KeyError::TpmCommandFailed(format!("{:?}", e)))?;
            // TSS returns a Vec<u8>; copy into fixed array.
            if bytes.len() < 8 {
                return Err(KeyError::TpmCommandFailed(
                    format!("GetRandom returned {} bytes, expected 8", bytes.len()),
                ));
            }
            let mut arr = [0u8; 8];
            arr.copy_from_slice(&bytes[..8]);
            Ok(u64::from_ne_bytes(arr))
        }
    }
}

// ── resolve() — entry point used by main.rs ──────────────────────────────────

/// Try the TPM first; on any failure fall back visibly to the compile-time key.
///
/// `compile_time_key` is the per-build fallback generated by `spica/build.rs`.
/// We pass it in (rather than reading it inside this crate) because the build
/// script that generates it also compiles the eBPF program and belongs with
/// the spica binary.
///
/// On non-Linux hosts (or Linux hosts without a TPM), `resolve` goes straight
/// to the fallback path.
pub fn resolve(compile_time_key: u64) -> (u64, KeyOrigin) {
    #[cfg(target_os = "linux")]
    {
        if let Ok(mut tpm) = crate::linux_tpm::TpmKeySource::new() {
            if let Ok(k) = tpm.get_random_key() {
                return (k, KeyOrigin::Tpm);
            }
        }
    }
    fallback(compile_time_key)
}

fn fallback(compile_time_key: u64) -> (u64, KeyOrigin) {
    eprintln!("[KEY]        ╔════════════════════════════════════════════╗");
    eprintln!("[KEY]        ║  INSECURE MODE — TPM UNAVAILABLE            ║");
    eprintln!("[KEY]        ║  Compile-time key in use.                  ║");
    eprintln!("[KEY]        ║  Recoverable from the binary.              ║");
    eprintln!("[KEY]        ║  Install on a TPM-equipped host for prod.  ║");
    eprintln!("[KEY]        ╚════════════════════════════════════════════╝");
    (compile_time_key, KeyOrigin::CompileTime)
}

// ── Integrity token derivation ───────────────────────────────────────────────
//
// SipHash-1-3 here is a *correct MAC use case* — deriving the integrity canary
// from BASE_KEY such that sc_canary[0] (an enumerable named map, readable by
// root) does not reveal BASE_KEY. This is distinct from the XOR obfuscation
// layer in spica-common, which is read-leakage defense (not a MAC, not a
// cipher, structurally vulnerable to known-plaintext — see README).

/// Derive the 64-bit integrity canary from BASE_KEY via SipHash-1-3.
///
/// Properties:
/// - Deterministic: same BASE_KEY always produces the same token.
/// - Not invertible: `sc_canary[0]` (readable by root) doesn't reveal BASE_KEY.
/// - Cheap: one SipHash-1-3 invocation per startup, not per event.
pub fn derive_integrity_token(base_key: u64) -> u64 {
    // Fold the 8-byte base_key into a 16-byte SipHash key by repeating it.
    // The input payload is the constant tag b"SPiCaINT" which binds the
    // derivation to this specific use (defends against token reuse from
    // any other SipHash(key, ...) caller in the same address space).
    let key_bytes = base_key.to_ne_bytes();
    let mut k = [0u8; 16];
    k[..8].copy_from_slice(&key_bytes);
    k[8..].copy_from_slice(&key_bytes);

    let mut h = SipHasher13::new_with_key(&k);
    h.write(b"SPiCaINT");
    h.finish()
}

// ── Tests ────────────────────────────────────────────────────────────────────
//
// All tests below run on Mac. The TpmKeySource impl is cfg(target_os = "linux")
// so it's not exercised here — first Linux run will cover it.

#[cfg(test)]
mod tests {
    use super::*;

    /// Test-only key source with a fixed value.
    pub struct StaticKey(pub u64);
    impl KeySource for StaticKey {
        fn get_random_key(&mut self) -> Result<u64, KeyError> { Ok(self.0) }
    }

    // ── KeySource impls ──────────────────────────────────────────────────────

    #[test]
    fn compile_time_key_returns_its_value() {
        let mut k = CompileTimeKey(0x0123_4567_89ab_cdef);
        assert_eq!(k.get_random_key().unwrap(), 0x0123_4567_89ab_cdef);
    }

    #[test]
    fn static_key_returns_its_value() {
        let mut k = StaticKey(42);
        assert_eq!(k.get_random_key().unwrap(), 42);
    }

    // ── derive_integrity_token ───────────────────────────────────────────────

    #[test]
    fn derive_integrity_token_is_deterministic() {
        let key = 0xdead_beef_cafe_babe;
        assert_eq!(derive_integrity_token(key), derive_integrity_token(key));
    }

    #[test]
    fn derive_integrity_token_is_not_invertible_to_key() {
        // The token is a u64 derived from the key. Verify that simple
        // inversions (XOR, negation, byte-swap) don't recover the key.
        let key = 0x0123_4567_89ab_cdef;
        let token = derive_integrity_token(key);
        assert_ne!(token, key, "token should not equal key");
        assert_ne!(token, !key, "token should not be bitwise-not of key");
        assert_ne!(token, key.swap_bytes(), "token should not be byte-swap of key");
        assert_ne!(token, 0, "token should not be zero");
        assert_ne!(token, u64::MAX, "token should not be all-ones");
    }

    #[test]
    fn derive_integrity_token_different_keys_differ() {
        let a = derive_integrity_token(0x1111_1111_1111_1111);
        let b = derive_integrity_token(0x2222_2222_2222_2222);
        assert_ne!(a, b, "different keys must produce different tokens");
    }

    #[test]
    fn derive_integrity_token_handles_zero_key() {
        // Zero key is a degenerate but valid input. Output should still be
        // deterministic and non-zero (SipHash of "SPiCaINT" with zero key).
        let token = derive_integrity_token(0);
        assert_ne!(token, 0, "zero key should still produce a non-zero token");
    }

    // ── resolve() fallback path ──────────────────────────────────────────────
    //
    // On Mac (no TPM), resolve() always falls back. We test that the fallback
    // returns the compile-time key passed in. The stderr banner is harder to
    // assert on without capturing stderr; we just verify the function returns
    // the right value.

    #[test]
    fn resolve_returns_compile_time_key_when_tpm_unavailable() {
        // On Mac this is the only path. On Linux without a TPM it's also the path.
        // On Linux with a TPM this test would fail (different value returned) —
        // so we only run it on non-Linux OR we'd need to mock. Skip on Linux
        // to keep the test deterministic.
        if cfg!(target_os = "linux") {
            return; // TPM might be present; test would be flaky
        }
        let (key, origin) = resolve(0xa5a5_a5a5_a5a5_a5a5);
        assert_eq!(key, 0xa5a5_a5a5_a5a5_a5a5);
        assert_eq!(origin, KeyOrigin::CompileTime);
    }

    #[test]
    fn fallback_returns_provided_key() {
        // Direct test of the fallback function (bypasses TPM check).
        let (key, origin) = fallback(0x1234);
        assert_eq!(key, 0x1234);
        assert_eq!(origin, KeyOrigin::CompileTime);
    }
}
